#!/usr/bin/env python

##############################################################
# whatmp3 - Convert FLAC to mp3, create what.cd torrent.
# Created by shardz (logik.li) and demonstar55
##############################################################

import os
import re
import fnmatch
import shutil
from optparse import OptionParser
import threading

VERSION = "3.4"

### BEGIN CONFIGURATION ###

# Output folder unless specified:
data_dir = os.getcwd()

# Torrents are placed in this directory
torrent_dir = data_dir

# Do you want to move additional files (.jpg, .log, etc)?
moveother = 1

# Do you want to zeropad tracknumbers? (1 => 01, 2 => 02 ...)
zeropad = 1

# Do you want to dither FLACs to 16/44 before encoding?
dither = 0

# Specify tracker ("http://tracker.what.cd:34000/")
tracker = "http://tracker.what.cd:34000/"

# Specify torrent passkey
passkey = "tracker_passkey_here"

# Max number of threads (ex: Normal: 1, Dual-core = 2, Hyperthreaded Dual-core = 4)
max_threads = 4

# Default encoding options
enc_options = {
    '320':  {'enc': 'lame',     'opts': '-b 320 --ignore-tag-errors'},
    'V0':   {'enc': 'lame',     'opts': '-V 0 --vbr-new --ignore-tag-errors'},
    'V2':   {'enc': 'lame',     'opts': '-V 2 --vbr-new --ignore-tag-errors'},
    'Q8':   {'enc': 'oggenc',   'opts': '-q 8'},
    'AAC':  {'enc': 'neroAacEnc',   'opts': '-br 320000'},
    'ALAC': {'enc': 'ffmpeg',   'opts': '-i - -acodec alac'},
    'FLAC': {'enc': 'flac',     'opts': '--best'}
}

# Default codecs - these are used if the --original option is specified
default_codecs = ['V0', 'V2', 'Q8', '320', 'AAC']

### END CONFIGURATION ###

codecs = []

# os.system() and os.popen() have issues with `
def escape(pattern):
    pattern = re.sub('`', '\`', pattern)
    return pattern

def esc(pattern):
    pattern = re.sub('"', '\\"', pattern)
    return pattern

class Transcode(threading.Thread):
    def __init__(self, file, flacdir, mp3_dir, codec, options, cv):
        threading.Thread.__init__(self)
        self.file = file
        self.flacdir = flacdir
        self.mp3_dir = mp3_dir
        self.codec = codec
        self.options = options
        self.cv = cv

    def run(self):
        tags = {}
        for tag in ('TITLE', 'ALBUM', 'ARTIST', 'TRACKNUMBER', 'GENRE', 'COMMENT', 'DATE'):
            tagcommand = 'metaflac --show-tag=' + esc(tag) + ' "' + esc(self.file) + '"'
            temp = re.sub('\S.*=', '', os.popen(escape(tagcommand)).read().rstrip())
            tags.update({tag:temp})
            del temp

        if self.options.zeropad and len(tags['TRACKNUMBER']) == 1:
            tags['TRACKNUMBER'] = '0' + tags['TRACKNUMBER']

        mp3_filename = re.sub(re.escape(self.flacdir), self.mp3_dir, self.file)
        mp3_filename = re.sub('\.flac$', '', mp3_filename)
        if not os.path.exists(os.path.dirname(mp3_filename)):
            os.makedirs(os.path.dirname(mp3_filename))

        flac_command = ''

        if enc_options[self.codec]['enc'] == 'lame':
            flac_command = 'lame -S %s --tt "%s" --tl "%s" --ta "%s" --tn "%s" --tg "%s" --ty "%s" --add-id3v2 - "%s.mp3" 2>&1'
        elif enc_options[self.codec]['enc'] == 'oggenc':
            flac_command = 'oggenc -Q %s -t "%s" -l "%s" -a "%s" -N "%s" -G "%s" -d "%s" -o "%s.ogg" - 2>&1'
        elif enc_options[self.codec]['enc'] == 'ffmpeg':
            flac_command = 'ffmpeg %s -metadata title="%s" -metadata album="%s" -metadata author="%s" -metadata track="%s" -metadata genre="%s" -metadata date="%s" "%s.m4a" 2>&1'
        elif enc_options[self.codec]['enc'] == 'neroAacEnc':
            flac_command = 'neroAacEnc %s -if - -of "%s.m4a" 2>&1 && neroAacTag "%s.m4a" -meta:title="%s" -meta:album="%s" -meta:artist="%s" -meta:track="%s" -meta:genre="%s" -meta:year="%s"'
        elif enc_options[self.codec]['enc'] == 'flac':
            if self.options.replaygain:
                flac_command = 'flac %s --replay-gain -T "TITLE=%s" -T "ALBUM=%s" -T "ALBUM=%s" -T "TRACKNUMBER=%s" -T "GENRE=%s" -T "DATE=%s" -o "%s.flac" - 2>&1'
            else:
                flac_command = 'flac %s -T "TITLE=%s" -T "ALBUM=%s" -T "ALBUM=%s" -T "TRACKNUMBER=%s" -T "GENRE=%s" -T "DATE=%s" -o "%s.flac" - 2>&1'

        dither_command = 'sox -t wav - -b 16 -t wav - rate 44100 dither'

        if enc_options[self.codec]['enc'] == 'neroAacEnc':
            if self.options.dither:
                flac_command = 'flac -dc -- "' + esc(self.file) + '" | ' + dither_command + ' | ' + flac_command % (esc(enc_options[self.codec]['opts']), esc(mp3_filename), esc(mp3_filename), esc(tags['TITLE']), esc(tags['ALBUM']), esc(tags['ARTIST']), esc(tags['TRACKNUMBER']), esc(tags['GENRE']), esc(tags['DATE']))
            else:
                flac_command = 'flac -dc -- "' + esc(self.file) + '" | ' + flac_command % (esc(enc_options[self.codec]['opts']), esc(mp3_filename), esc(mp3_filename), esc(tags['TITLE']), esc(tags['ALBUM']), esc(tags['ARTIST']), esc(tags['TRACKNUMBER']), esc(tags['GENRE']), esc(tags['DATE']))
        elif enc_options[self.codec]['enc'] == 'flac' and self.options.dither:
            # seems like FLAC and SoX don't work together via pipes. use files instead.
            flac_command = 'flac -dc -- "' + esc(self.file) + '" | ' + dither_command + ' > "' + esc(mp3_filename) + '.wav"; ' + flac_command % (esc(enc_options[self.codec]['opts']), esc(tags['TITLE']), esc(tags['ALBUM']), esc(tags['ARTIST']), esc(tags['TRACKNUMBER']), esc(tags['GENRE']), esc(tags['DATE']), esc(mp3_filename)) + ' < "' + esc(mp3_filename) + '.wav"'
        else:
            if self.options.dither:
                flac_command = 'flac -dc -- "' + esc(self.file) + '" | ' + dither_command + ' | ' + flac_command % (esc(enc_options[self.codec]['opts']), esc(tags['TITLE']), esc(tags['ALBUM']), esc(tags['ARTIST']), esc(tags['TRACKNUMBER']), esc(tags['GENRE']), esc(tags['DATE']), esc(mp3_filename))
            else:
                flac_command = 'flac -dc -- "' + esc(self.file) + '" | ' + flac_command % (esc(enc_options[self.codec]['opts']), esc(tags['TITLE']), esc(tags['ALBUM']), esc(tags['ARTIST']), esc(tags['TRACKNUMBER']), esc(tags['GENRE']), esc(tags['DATE']), esc(mp3_filename))

        if self.options.verbose:
            print(escape(flac_command))
        os.system(escape(flac_command))

        self.cv.acquire()
        self.cv.notify_all()
        self.cv.release()

        return 0

def add_enc_option(option, opt, value, parser):
    codecs.append(opt[2:])

def main():
    # Parse options and arguments
    usage_text = "%prog [options] [--320 --V2 --Q8 --AAC ...] /path/to/FLAC"
    info_text = "Depends on flac, metaflac, mktorrent, and optionally oggenc, lame, neroAacEnc, neroAacTag, mp3gain, aacgain, and vorbisgain."
    parser = OptionParser(usage=usage_text, version="%prog " + VERSION, epilog=info_text)
    parser.add_option('-v', '--verbose',    action='store_true',    dest='verbose',     default=False,  help='increase verbosity (Default: False)')
    parser.add_option('-n', '--notorrent',  action='store_true',    dest='notorrent',   default=False,  help='will not create a torrent after conversion (Default: False)')
    parser.add_option('--nolog',        action='store_true',    dest='nolog',       default=False,  help='will not move log files after conversion (Default: False)')
    parser.add_option('--nocue',        action='store_true',    dest='nocue',       default=False,  help='will not move cue files after conversion (Default: False)')
    parser.add_option('-m', '--moveother',  action='store_true',    dest='moveother',   default=moveother,  help='move additional files (Default: True)')
    parser.add_option('-p', '--passkey',    dest='passkey',     default=passkey,    help='tracker PASSKEY', metavar='PASSKEY')
    parser.add_option('-t', '--tracker',    dest='tracker',     default=tracker,    help='tracker URL (Default: "http://tracker.what.cd:34000/")', metavar='URL')
    parser.add_option('-o', '--output', dest='data_dir',      default=data_dir,     help='set the data output PATH', metavar='PATH')
    parser.add_option('--torrent_dir', dest='torrent_dir',      default=torrent_dir,     help='set the torrent output PATH', metavar='PATH')
    parser.add_option('-z', '--zeropad',    action='store_true',    dest='zeropad',     default=zeropad,    help='zeropad track numbers (Default: True)')
    parser.add_option('-d', '--dither', action='store_true',    dest='dither',      default=dither, help='dither FLACs to 16/44 before encoding (Default: False)')
    parser.add_option('-r', '--replaygain', action='store_true',    dest='replaygain',  default=False,  help='add ReplayGain to new files (Default: False)')
    parser.add_option('--threads',      type="int",     dest='max_threads', default=max_threads,    help='set number of threads THREADS (Default: 4)', metavar='THREADS')
    parser.add_option('-c', '--original',     action="store_true", dest='original', default=False, help='create a torrent for the original FLACs and convert to all of your default formats (Default:False)')

    for enc_opt in enc_options.keys():
        parser.add_option("--" + enc_opt, action="callback", callback=add_enc_option)

    (options, flacdirs) = parser.parse_args()

    if options.original:
        for codec in default_codecs:
            if codec not in codecs:
                codecs.append(codec)

    if len(flacdirs) < 1:
        parser.error("Incorrect number of arguments")

    if not options.data_dir.endswith('/'):
        options.data_dir += '/'

    if not options.torrent_dir.endswith('/'):
        options.torrent_dir += '/'

    if len(codecs) == 0:
        print('You need to provide at least one format to transcode to (320, V0, Q8 ...)')
        exit()

    for flacdir in flacdirs:
        flacdir = os.path.abspath(flacdir)
        flacfiles = []

        for dirpath, dirs, files in os.walk(flacdir, topdown=False):
            for name in files:
                if fnmatch.fnmatch(name, '*.flac'):
                    flacfiles.append(os.path.join(dirpath, name))

        if options.original:
            print('Working with FLAC...')

            if options.torrent_dir and options.passkey and options.tracker and not options.notorrent:
                if options.verbose: print('Creating torrent...')
                torrent_command = 'mktorrent -p -a %s/announce -o "%s.torrent" "%s"' % (options.tracker + options.passkey, esc(options.torrent_dir + os.path.basename(flacdir)), esc(flacdir))
                if options.verbose: print(escape(torrent_command))
                os.system(escape(torrent_command))

            print('Finished working with FLAC')

        for codec in codecs:
            mp3_dir = options.data_dir + os.path.basename(flacdir)
            if 'FLAC' in flacdir:
                mp3_dir = re.sub(re.compile('FLAC', re.I), codec, mp3_dir)
            else:
                mp3_dir = mp3_dir + " (" + codec + ")"
                if codec != 'FLAC':
                    mp3_dir = re.sub(re.compile('FLAC', re.I), '', mp3_dir)
            if options.dither:
                if '24' in flacdir and '96' in flacdir:
                    # XXX: theoretically, this could replace part of the album title too.
                    # e.g. "26 days in 96 castles - [24-96]" would become "16 days in 44 castles - [16-44]"
                    mp3_dir = re.sub(re.compile('24', re.I), '16', mp3_dir)
                    mp3_dir = re.sub(re.compile('96', re.I), '44', mp3_dir)
                else:
                    mp3_dir += " [16-44]"

            if not os.path.exists(mp3_dir):
                os.makedirs(mp3_dir)

            print('Encoding with ' + codec + ' started...')

            threads = []
            cv = threading.Condition()
            for file in flacfiles:
                cv.acquire()
                while((threading.activeCount() == options.max_threads + 1) or (options.max_threads == 0 and threading.activeCount() == 2)):
                    cv.wait()
                cv.release()
                t=Transcode(file, flacdir, mp3_dir, codec, options, cv)
                t.start()
                threads.append(t)

            for t in threads:
                t.join()

            if codec == 'FLAC' and options.dither:
                # discard the temporary .WAVs we created to circumvent the FLAC bug.
                os.system('rm "' + esc(mp3_dir) + '"/*.wav')

            print('\nEncoding with ' + codec + ' finished.')

            if options.moveother:
                if options.verbose: print('Moving other files...')
                for dirpath, dirs, files in os.walk(flacdir, topdown=False):
                    for name in files:
                        if options.nolog and fnmatch.fnmatch(name, '*.log'):
                            continue
                        if options.nocue and fnmatch.fnmatch(name, '*.cue'):
                            continue
                        if not fnmatch.fnmatch(name, '*.flac') and not fnmatch.fnmatch(name, '*.m3u'):
                            d = re.sub(re.escape(flacdir), mp3_dir, dirpath)
                            if not os.path.exists(d):
                                os.makedirs(d)
                            shutil.copy(os.path.join(dirpath, name), d)

            if options.replaygain:
                if options.verbose: print('Applying replay gain...')

                for dirpath, dirs, files in os.walk(mp3_dir, topdown=False):
                    for name in dirs:
                        if enc_options[codec]['enc'] == 'lame':
                            os.system(escape('mp3gain -q -c -s i "' + os.path.join(dirpath, name) + '"/*.mp3'))
                        if enc_options[codec]['enc'] == 'oggenc':
                            os.system(escape('vorbisgain -qafrs "' + os.path.join(dirpath, name) + '"/*.ogg'))
                        if enc_options[codec]['enc'] == 'neroAacEnc':
                            os.system(escape('aacgain -q -c "' + os.path.join(dirpath, name) + '"/*.m4a'))

            if options.torrent_dir and options.passkey and options.tracker and not options.notorrent:
                if options.verbose: print('Creating torrent...')
                torrent_command = 'mktorrent -p -a %s/announce -o "%s.torrent" "%s"' % (options.tracker + options.passkey, escape(options.torrent_dir + os.path.basename(mp3_dir)), mp3_dir)
                if options.verbose: print(escape(torrent_command))
                os.system(escape(torrent_command))

        if options.verbose: print('All done with ' + flacdir + ' ...')
    return 0

if __name__ == '__main__':
    main()
